### ISSUE TITLE
Website bugging out

### ISSUE THREAD

**Issue by lapidary-master** [CameronWDMorgan/JSCammie-Website#9]
`An error occurred: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

Some possible tomfoolery with the JSON the site parses?

Looking into devtools, it's something to do with https://raw.githubusercontent.com/CameronWDMorgan/JSCammie-Website/main/scripts/ai-form.js ?

**Comment by CameronWDMorgan** [comment]
Does this still occur now?
